// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteBooksBookIDHandlerFunc turns a function with the right signature into a delete books book ID handler
type DeleteBooksBookIDHandlerFunc func(DeleteBooksBookIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBooksBookIDHandlerFunc) Handle(params DeleteBooksBookIDParams) middleware.Responder {
	return fn(params)
}

// DeleteBooksBookIDHandler interface for that can handle valid delete books book ID params
type DeleteBooksBookIDHandler interface {
	Handle(DeleteBooksBookIDParams) middleware.Responder
}

// NewDeleteBooksBookID creates a new http.Handler for the delete books book ID operation
func NewDeleteBooksBookID(ctx *middleware.Context, handler DeleteBooksBookIDHandler) *DeleteBooksBookID {
	return &DeleteBooksBookID{Context: ctx, Handler: handler}
}

/*DeleteBooksBookID swagger:route DELETE /books/{bookID} deleteBooksBookId

Delete a book by ID

*/
type DeleteBooksBookID struct {
	Context *middleware.Context
	Handler DeleteBooksBookIDHandler
}

func (o *DeleteBooksBookID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteBooksBookIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
