// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteBooksBookIDNoContentCode is the HTTP code returned for type DeleteBooksBookIDNoContent
const DeleteBooksBookIDNoContentCode int = 204

/*DeleteBooksBookIDNoContent No Content

swagger:response deleteBooksBookIdNoContent
*/
type DeleteBooksBookIDNoContent struct {
}

// NewDeleteBooksBookIDNoContent creates DeleteBooksBookIDNoContent with default headers values
func NewDeleteBooksBookIDNoContent() *DeleteBooksBookIDNoContent {

	return &DeleteBooksBookIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteBooksBookIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteBooksBookIDInternalServerErrorCode is the HTTP code returned for type DeleteBooksBookIDInternalServerError
const DeleteBooksBookIDInternalServerErrorCode int = 500

/*DeleteBooksBookIDInternalServerError Internal Server Error

swagger:response deleteBooksBookIdInternalServerError
*/
type DeleteBooksBookIDInternalServerError struct {
}

// NewDeleteBooksBookIDInternalServerError creates DeleteBooksBookIDInternalServerError with default headers values
func NewDeleteBooksBookIDInternalServerError() *DeleteBooksBookIDInternalServerError {

	return &DeleteBooksBookIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteBooksBookIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
