// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/delgus/swagger-rest/internal/models"
)

// GetBooksBookIDOKCode is the HTTP code returned for type GetBooksBookIDOK
const GetBooksBookIDOKCode int = 200

/*GetBooksBookIDOK OK

swagger:response getBooksBookIdOK
*/
type GetBooksBookIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewGetBooksBookIDOK creates GetBooksBookIDOK with default headers values
func NewGetBooksBookIDOK() *GetBooksBookIDOK {

	return &GetBooksBookIDOK{}
}

// WithPayload adds the payload to the get books book Id o k response
func (o *GetBooksBookIDOK) WithPayload(payload *models.Book) *GetBooksBookIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books book Id o k response
func (o *GetBooksBookIDOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksBookIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBooksBookIDNotFoundCode is the HTTP code returned for type GetBooksBookIDNotFound
const GetBooksBookIDNotFoundCode int = 404

/*GetBooksBookIDNotFound Not Found

swagger:response getBooksBookIdNotFound
*/
type GetBooksBookIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksBookIDNotFound creates GetBooksBookIDNotFound with default headers values
func NewGetBooksBookIDNotFound() *GetBooksBookIDNotFound {

	return &GetBooksBookIDNotFound{}
}

// WithPayload adds the payload to the get books book Id not found response
func (o *GetBooksBookIDNotFound) WithPayload(payload *models.Error) *GetBooksBookIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books book Id not found response
func (o *GetBooksBookIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksBookIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
