// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutBooksNoContentCode is the HTTP code returned for type PutBooksNoContent
const PutBooksNoContentCode int = 204

/*PutBooksNoContent No Content

swagger:response putBooksNoContent
*/
type PutBooksNoContent struct {
}

// NewPutBooksNoContent creates PutBooksNoContent with default headers values
func NewPutBooksNoContent() *PutBooksNoContent {

	return &PutBooksNoContent{}
}

// WriteResponse to the client
func (o *PutBooksNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutBooksInternalServerErrorCode is the HTTP code returned for type PutBooksInternalServerError
const PutBooksInternalServerErrorCode int = 500

/*PutBooksInternalServerError Internal Server Error

swagger:response putBooksInternalServerError
*/
type PutBooksInternalServerError struct {
}

// NewPutBooksInternalServerError creates PutBooksInternalServerError with default headers values
func NewPutBooksInternalServerError() *PutBooksInternalServerError {

	return &PutBooksInternalServerError{}
}

// WriteResponse to the client
func (o *PutBooksInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
