// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutBooksHandlerFunc turns a function with the right signature into a put books handler
type PutBooksHandlerFunc func(PutBooksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutBooksHandlerFunc) Handle(params PutBooksParams) middleware.Responder {
	return fn(params)
}

// PutBooksHandler interface for that can handle valid put books params
type PutBooksHandler interface {
	Handle(PutBooksParams) middleware.Responder
}

// NewPutBooks creates a new http.Handler for the put books operation
func NewPutBooks(ctx *middleware.Context, handler PutBooksHandler) *PutBooks {
	return &PutBooks{Context: ctx, Handler: handler}
}

/*PutBooks swagger:route PUT /books putBooks

Update a book by ID

*/
type PutBooks struct {
	Context *middleware.Context
	Handler PutBooksHandler
}

func (o *PutBooks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutBooksParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
